version: '3.8'

services:
  postgres:
    image: postgres:10.22-alpine
    container_name: bisque-postgres
    environment:
      POSTGRES_USER: bisque
      POSTGRES_PASSWORD: bisque2022
      POSTGRES_DB: bisque
    ports:
      - "128.111.185.111:5432:5432"
    volumes:
      - /data/bisque-testbed/pgdata:/var/lib/postgresql/data # Ensure this path exists on the host
    networks:
      - bisque-net
      # - host

  vrl-4090.ece.ucsb.edu:
    image: bisque:latest
    container_name: bisque-prod
    restart: unless-stopped
    depends_on:
      - postgres
    # network_mode: "host"
    stdin_open: true
    tty: true
    ports:
      - "128.111.185.111:8080:8080"
      - "128.111.185.111:27000:27000"
      # - "128.111.185.111:6443:6443"
      # - "6443:6444"
    volumes:
      - /data/bisque-testbed/bisque-data:/source/data # Ensure this path exists on the host
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/charvi/bisque_workspace/Bisque_Module_Generator/Modules:/source/modules:ro # Ensure this path exists on the host
      - /home/charvi/bisque_workspace/bisqueUCSB/source:/mnt/bisque-dev  # <-- Mount your local code here only use for development
      - ./entrypoint.sh:/mnt/copy_and_restart.sh 
      - ./k3s.yaml:/root/.kube/k3s_client.yaml # this file i got by installing k3s on the host and changine inside the server name instead of local
    environment:
      BISQUE_DBURL: "postgresql://bisque:bisque2022@postgres:5432/bisque"
    networks:
      - bisque-net
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
      # - host

networks: 
  # host:
  bisque-net:

